#!/usr/bin/env python3
"""Write the KiCad schematic and libraries that match the routed board.

    python3 scripts/make_schematic.py pcb/ultra-choc-wings.kicad_pcb [board_to_link.kicad_pcb]

By default the board is both read and linked. If KiCad's python module is too
old to open the board (it was saved by a newer KiCad), read an older copy of
the same board and name the real one as the second argument: the files are
written next to it and its footprints are linked by editing its text.

The board is generated by ergogen, so it has no schematic of its own. This
reads every footprint and pad net from the board and writes, next to it:

  ucw.pretty/                  one footprint per part type, taken from the board
  ucw.kicad_sym                one symbol per part type
  ultra-choc-wings.kicad_sch   every part with its nets (as net labels)
  fp-lib-table, sym-lib-table  so the project finds both libraries

It then points each footprint on the board at its library footprint and at
its schematic symbol, so "Update PCB from Schematic" and cross-probing match
part for part. Symbol UUIDs come from the reference designator, so rerunning
this after a reroute gives the same files.
"""
import os
import re
import sys
import uuid

import pcbnew

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jlcpcb import PARTS, value_of  # noqa: E402

PROJECT = "ultra-choc-wings"
LIB = "ucw"  # library nickname; the ergogen footprints already use it
NS = uuid.UUID("6f1b2c1e-8d1f-4c55-9a51-3c1f0e5e7a10")
ROOT = str(uuid.uuid5(NS, "root-sheet"))


def uid(*key):
    return str(uuid.uuid5(NS, "/".join(key)))


# --- symbols ----------------------------------------------------------------
# Each symbol: pins as (number, name, x, y, angle, length) in symbol units (mm,
# y up), graphics as raw s-expressions, and where Reference/Value sit.

FONT = "(effects (font (size 1.27 1.27)))"
FONT_HIDE = "(effects (font (size 1.27 1.27)) hide)"


def two_pin(graphics, length=2.54):
    return [("1", "~", -5.08, 0, 0, length), ("2", "~", 5.08, 0, 180, length)], graphics


def poly(*pts, fill="none"):
    xy = " ".join(f"(xy {x} {y})" for x, y in pts)
    return f"(polyline (pts {xy}) (stroke (width 0.254) (type default)) (fill (type {fill})))"


def circle(x, y, r, fill="none"):
    return f"(circle (center {x} {y}) (radius {r}) (stroke (width 0.254) (type default)) (fill (type {fill})))"


def rect(x0, y0, x1, y1, fill="none"):
    return f"(rectangle (start {x0} {y0}) (end {x1} {y1}) (stroke (width 0.254) (type default)) (fill (type {fill})))"


DIODE = [poly((1.27, 1.27), (1.27, -1.27), (-1.27, 0), (1.27, 1.27)), poly((-1.27, 1.27), (-1.27, -1.27))]

SYMBOLS = {
    # name: (pins, graphics, description, hide pin names)
    "R": (*two_pin([rect(-2.54, 1.016, 2.54, -1.016)]), "Resistor", True),
    "C": (*two_pin([poly((-0.508, 1.524), (-0.508, -1.524)), poly((0.508, 1.524), (0.508, -1.524))], 4.572),
          "Capacitor", True),
    "D": (*two_pin(DIODE, 3.81), "Diode, pin 1 = cathode", True),
    "D_Schottky": (*two_pin([DIODE[0], poly((-1.778, 1.016), (-1.778, 1.27), (-1.27, 1.27), (-1.27, -1.27),
                                            (-0.762, -1.27), (-0.762, -1.016))], 3.81),
                   "Schottky diode, pin 1 = cathode", True),
    "LED": (*two_pin(DIODE + [poly((-0.254, 1.524), (0.762, 2.54)), poly((0.762, 2.54), (0.254, 2.54)),
                              poly((0.762, 2.54), (0.762, 2.032)), poly((0.762, 1.524), (1.778, 2.54)),
                              poly((1.778, 2.54), (1.27, 2.54)), poly((1.778, 2.54), (1.778, 2.032))], 3.81),
            "LED, pin 1 = cathode", True),
    "SW_Push": (*two_pin([circle(-2.032, 0, 0.508), circle(2.032, 0, 0.508), poly((-2.54, 1.524), (2.54, 1.524)),
                          poly((0, 1.524), (0, 2.794))], 2.54), "Key switch (Kailh PG1316S)", True),
    "Battery_Cell": (*two_pin([poly((-0.508, 1.778), (-0.508, -1.778)), poly((0.508, 0.889), (0.508, -0.889)),
                               poly((-2.032, 1.27), (-1.016, 1.27)), poly((-1.524, 1.778), (-1.524, 0.762))], 4.572),
                     "Coin cell, pin 1 = +", True),
    "Q_NMOS_GSD": ([("1", "G", -5.08, 0, 0, 2.54), ("3", "D", 2.54, 5.08, 270, 2.54), ("2", "S", 2.54, -5.08, 90, 2.54)],
                   [poly((-1.778, 1.27), (-1.778, -1.27)), poly((-1.016, 1.524), (-1.016, -1.524)),
                    poly((-1.016, 1.27), (2.54, 1.27), (2.54, 2.54)), poly((-1.016, -1.27), (2.54, -1.27), (2.54, -2.54)),
                    poly((-1.016, 0), (0.508, 0)), poly((0, 0.508), (0.508, 0), (0, -0.508), (0, 0.508), fill="outline"),
                    circle(0.508, 0, 3.048)],
                   "N-channel MOSFET, SOT-23 (1 = G, 2 = S, 3 = D)", True),
    "SW_SPDT": ([("2", "~", -5.08, 0, 0, 2.54), ("1", "~", 5.08, 2.54, 180, 2.54), ("3", "~", 5.08, -2.54, 180, 2.54)],
                [circle(-2.032, 0, 0.508), circle(2.032, 2.54, 0.508), circle(2.032, -2.54, 0.508),
                 poly((-1.524, 0.254), (1.524, 2.286))],
                "Slide switch, SPDT (pin 2 = common)", True),
    "Pad": ([("1", "~", -5.08, 0, 0, 3.81)], [circle(0, 0, 1.27)], "Solder pad", True),
    "MountingHole": ([], [circle(0, 0, 1.27), circle(0, 0, 2.032)], "M2 mounting hole", True),
}

# XIAO nRF52840: footprint pads 1-7 are 5V, GND, 3V3, D10..D7; 18-24 are D6..D0.
XIAO_LEFT = [("1", "5V"), ("2", "GND"), ("3", "3V3"), ("4", "D10"), ("5", "D9"), ("6", "D8"), ("7", "D7")]
XIAO_RIGHT = [(str(18 + i), f"D{6 - i}") for i in range(7)]
SYMBOLS["XIAO_nRF52840"] = (
    [(n, name, -12.7, 7.62 - 2.54 * i, 0, 2.54) for i, (n, name) in enumerate(XIAO_LEFT)] +
    [(n, name, 12.7, 7.62 - 2.54 * i, 180, 2.54) for i, (n, name) in enumerate(XIAO_RIGHT)],
    [rect(-10.16, 10.16, 10.16, -10.16, fill="background")],
    "Seeed XIAO nRF52840 (BLE), flippable footprint", False)

# Board footprint name -> symbol
SYMBOL_OF = {
    "CPG1316S01D02_reversible": "SW_Push",
    "REV_SOD123": "D",
    "REV_SOD323": "D",
    "REV_LED0603": "LED",
    "REV_0603": "R",
    "REV_0805": "C",
    "REV_SOT-23": "Q_NMOS_GSD",
    "REV_CR2032_BC2003": "Battery_Cell",
    "REV_SPDT_C128955": "SW_SPDT",
    "SMDPad": "Pad",
    "M2_NPTH": "MountingHole",
    "xiao-ble": "XIAO_nRF52840",
}


def symbol_def(name, prefix=""):
    pins, graphics, descr, hide_names = SYMBOLS[name]
    ref = {"Q_NMOS_GSD": "Q", "SW_Push": "SW", "SW_SPDT": "T", "Battery_Cell": "BT", "Pad": "PAD",
           "MountingHole": "H", "XIAO_nRF52840": "U", "D_Schottky": "D", "LED": "L"}.get(name, name[0])
    top = max([y for _, _, _, y, _, _ in pins] + [2]) + 1.27
    out = [f'(symbol "{prefix}{name}"' + (" (pin_names (offset 0) hide)" if hide_names else " (pin_names (offset 1.016))")
           + (" (in_bom no) (on_board yes)" if not pins else " (in_bom yes) (on_board yes)"),
           f'  (property "Reference" "{ref}" (at 0 {top + 1.27} 0) {FONT})',
           f'  (property "Value" "{name}" (at 0 {-top - 1.27} 0) {FONT})',
           f'  (property "Footprint" "" (at 0 0 0) {FONT_HIDE})',
           f'  (property "Datasheet" "~" (at 0 0 0) {FONT_HIDE})',
           f'  (property "ki_description" "{descr}" (at 0 0 0) {FONT_HIDE})',
           f'  (symbol "{name}_0_1" ' + " ".join(graphics) + ")"]
    pin_s = " ".join(
        f'(pin passive line (at {x} {y} {a}) (length {ln}) (name "{nm}" {FONT}) (number "{n}" {FONT}))'
        for n, nm, x, y, a, ln in pins)
    out.append(f'  (symbol "{name}_1_1" {pin_s})')
    return "\n".join(out) + ")"


# --- board ------------------------------------------------------------------

def parts(board):
    """Board footprints as dicts, sorted by reference."""
    out = []
    for fp in board.GetFootprints():
        nets = {}
        for pad in fp.Pads():
            if pad.GetNumber() and pad.GetNetname():
                nets[pad.GetNumber()] = pad.GetNetname()
        value = "XIAO nRF52840" if fp.GetReference().startswith("xiao") else value_of(fp)
        out.append({"ref": fp.GetReference(), "value": value,
                    "fp": str(fp.GetFPID().GetUniStringLibItemName()).split(":")[-1], "nets": nets, "obj": fp})
    key = lambda p: (re.sub(r"\d+$", "", p["ref"]), int(re.search(r"(\d*)$", p["ref"]).group(1) or 0))
    return sorted(out, key=key)


def export_footprints(board, libdir):
    os.makedirs(libdir, exist_ok=True)
    done = set()
    for fp in board.GetFootprints():
        name = str(fp.GetFPID().GetUniStringLibItemName()).split(":")[-1]
        if name in done:
            continue
        done.add(name)
        copy = pcbnew.FOOTPRINT(fp)
        if copy.IsFlipped():
            copy.Flip(copy.GetPosition(), False)
        copy.SetOrientationDegrees(0)
        copy.SetPosition(pcbnew.VECTOR2I(0, 0))
        for pad in copy.Pads():
            pad.SetNetCode(0)
        copy.SetReference("REF**")
        copy.SetFPID(pcbnew.LIB_ID("", name))
        path = os.path.join(libdir, name + ".kicad_mod")
        if os.path.exists(path):
            os.remove(path)
        pcbnew.FootprintSave(libdir, copy)
    return sorted(done)


# --- schematic --------------------------------------------------------------

def label_angle(pin_angle):
    return {0: 180, 180: 0, 270: 90, 90: 270}[pin_angle]


def gl(net, X, Y, angle, key):
    """Global label, so the net name is exactly the board's (a local label on
    the root sheet would become "/NAME")."""
    just = "left" if angle in (0, 90) else "right"
    return (f'(global_label "{net}" (shape passive) (at {X} {Y} {angle}) (fields_autoplaced) '
            f'(effects (font (size 1.27 1.27)) (justify {just})) (uuid {uid("label", *key)})\n'
            f'  (property "Intersheetrefs" "${{INTERSHEET_REFS}}" (at {X} {Y} 0) {FONT_HIDE}))')


def wire(a, b, key, items):
    items.append(f'(wire (pts (xy {a[0]} {a[1]}) (xy {b[0]} {b[1]})) (stroke (width 0) (type default)) '
                 f'(uuid {uid("wire", *key)}))')


def pin_xy(sym, n, x, y, rot=0):
    """Schematic position of pin `n` of a symbol placed at (x, y), rot 0 or 180."""
    for num, _, px, py, a, _ in SYMBOLS[sym][0]:
        if num == n:
            return (round(x + px, 2), round(y - py, 2)) if rot == 0 else (round(x - px, 2), round(y + py, 2))
    raise KeyError(n)


def place(sym, ref, value, fp_name, x, y, nets, lcsc, items, instances, rot=0, wired=()):
    """Place a symbol. Pins in `wired` get no label of their own: the caller
    draws a wire to the part they connect to and names that wire."""
    pins = SYMBOLS[sym][0]
    u = uid("sym", ref)
    props = [f'(property "Reference" "{ref}" (at {x} {y - 3.81 - (7.62 if sym == "XIAO_nRF52840" else 0)} 0) {FONT})',
             f'(property "Value" "{value}" (at {x} {y + 3.81 + (7.62 if sym == "XIAO_nRF52840" else 0)} 0) {FONT})',
             f'(property "Footprint" "{LIB}:{fp_name}" (at {x} {y} 0) {FONT_HIDE})',
             f'(property "Datasheet" "~" (at {x} {y} 0) {FONT_HIDE})']
    if lcsc:
        props.append(f'(property "LCSC" "{lcsc}" (at {x} {y} 0) {FONT_HIDE})')
    pin_uuids = " ".join(f'(pin "{n}" (uuid {uid("pin", ref, n)}))' for n, *_ in pins)
    items.append(f'(symbol (lib_id "{LIB}:{sym}") (at {x} {y} {rot}) (unit 1) (in_bom {"no" if not pins else "yes"}) '
                 f'(on_board yes) (dnp no) (uuid {u})\n  ' + "\n  ".join(props) + f"\n  {pin_uuids}\n"
                 f'  (instances (project "{PROJECT}" (path "/{ROOT}" (reference "{ref}") (unit 1)))))')
    for n, _, px, py, a, _ in pins:
        X, Y = pin_xy(sym, n, x, y, rot)
        net = nets.get(n)
        if net is None:
            items.append(f"(no_connect (at {X} {Y}) (uuid {uid('nc', ref, n)}))")
            continue
        if n in wired:
            continue
        items.append(gl(net, X, Y, label_angle((a + rot) % 360), (ref, n)))
    instances[ref] = u


def text(s, x, y, size=2.54):
    s = s.replace('"', '\\"')
    return (f'(text "{s}" (at {x} {y} 0) (effects (font (size {size} {size})) (justify left bottom)) '
            f'(uuid {uid("text", s)}))')


def g(v):
    """Snap to the 1.27 mm schematic grid."""
    return round(round(v / 1.27) * 1.27, 2)


def symbol_for(p):
    if p["value"] == "B5819W":
        return "D_Schottky"
    return SYMBOL_OF[p["fp"]]


def lcsc_for(p):
    part = PARTS.get(p["value"])
    return part[2] if part else ""


def write_schematic(plist, path):
    by_ref = {p["ref"]: p for p in plist}
    items, instances, placed = [], {}, set()

    def put(p, x, y, rot=0, wired=()):
        place(symbol_for(p), p["ref"], p["value"] or SYMBOL_OF[p["fp"]], p["fp"], g(x), g(y), p["nets"],
              lcsc_for(p), items, instances, rot, wired)
        placed.add(p["ref"])

    def link(a, pa, b, pb, ra=0, rb=0, angle=90):
        """Wire pin `pa` of part a to pin `pb` of part b and name the wire after
        the net they share, with a label standing on the wire."""
        (sa, xa, ya), (sb, xb, yb) = pos[a["ref"]], pos[b["ref"]]
        p1, p2 = pin_xy(sa, pa, xa, ya, ra), pin_xy(sb, pb, xb, yb, rb)
        assert a["nets"][pa] == b["nets"][pb], (a["ref"], pa, b["ref"], pb)
        key = (a["ref"], pa, b["ref"], pb)
        wire(p1, p2, key, items)
        mid = (round((p1[0] + p2[0]) / 2, 2), round((p1[1] + p2[1]) / 2, 2))
        items.append(gl(a["nets"][pa], mid[0], mid[1], angle, key))

    pos = {}

    def put_at(p, x, y, rot=0, wired=()):
        x, y = g(x), g(y)
        pos[p["ref"]] = (symbol_for(p), x, y)
        put(p, x, y, rot, wired)

    # Key matrix, one block per key. Each key is two chains, wired where two
    # parts share a net and labelled at the ends where the net goes elsewhere:
    #   row label - diode - SW - column label        (switch to its diode)
    #   LED_K label - LED - resistor - VCC3 label    (LED to its resistor)
    items.append(text("Key matrix (COL2ROW): switch, diode, per-key LED and its resistor", 25.4, 35.56, 3))
    keys = [p for p in plist if p["ref"].startswith("SW")]
    for i, sw in enumerate(keys):
        n = sw["ref"][2:]
        bx, by = 25.4 + (i % 6) * 91.44, 50.8 + (i // 6) * 63.5
        row = {r: by_ref[f"{r}{n}"] for r in ("D", "SW", "L", "R") if f"{r}{n}" in by_ref}
        d, s_, l, r = row.get("D"), row.get("SW"), row.get("L"), row.get("R")
        put_at(d, bx + 22.86, by + 5.08, 0, wired=("2",))
        put_at(s_, bx + 43.18, by + 5.08, 0, wired=("1",))
        link(d, "2", s_, "1", 0, 0, 90)
        put_at(l, bx + 22.86, by + 30.48, 0, wired=("2",))
        put_at(r, bx + 43.18, by + 30.48, 180, wired=("2",))
        link(l, "2", r, "2", 0, 180, 270)

    y0 = 254.0
    items.append(text("MCU: Seeed XIAO nRF52840 (flippable footprint)", 25.4, y0, 3))
    for p in plist:
        if p["fp"] == "xiao-ble":
            put_at(p, 76.2, y0 + 30.48)

    x0 = 172.72
    items.append(text("Power: CR2032 -> slide switch -> B5819W -> RAW, 2x 22uF on RAW", x0, y0, 3))
    items.append(text("Wire the RAW pad (PAD1) to the BAT+ pad under the XIAO.", x0, y0 + 5.08, 1.8))
    kind = {symbol_for(p): p for p in plist if symbol_for(p) in ("Battery_Cell", "SW_SPDT", "D_Schottky")}
    bt, sw, sd = kind["Battery_Cell"], kind["SW_SPDT"], kind["D_Schottky"]
    yp = y0 + 22.86
    # BT1 + -> slide switch (pin 1) ; common (pin 2) -> B5819W anode ; cathode = RAW
    put_at(bt, x0 + 20.32, yp, 180, wired=("1",))
    put_at(sw, x0 + 50.8, yp - 2.54, 180, wired=("1", "2"))
    put_at(sd, x0 + 76.2, yp - 2.54, 180, wired=("2",))
    link(bt, "1", sw, "1", 180, 180, 90)
    link(sw, "2", sd, "2", 180, 180, 90)
    for i, p in enumerate(q for q in plist if symbol_for(q) in ("C", "Pad")):
        put_at(p, x0 + 106.68 + i * 25.4, yp)

    items.append(text("LED driver: all LED cathodes switched to GND, PWM on D6, 100k pull-down", x0, y0 + 50.8, 3))
    q1 = next(p for p in plist if p["ref"].startswith("Q"))
    pd = by_ref["R19"]
    put_at(pd, x0 + 20.32, y0 + 73.66, 180, wired=("1",))
    put_at(q1, x0 + 45.72, y0 + 73.66, 0, wired=("1",))
    link(pd, "1", q1, "1", 180, 0, 90)

    items.append(text("Mounting holes", x0 + 203.2, y0 + 50.8, 3))
    rest = [p for p in plist if p["ref"] not in placed]
    for i, p in enumerate(rest):
        put_at(p, x0 + 213.36 + i * 20.32, y0 + 73.66)

    used = sorted({symbol_for(p) for p in plist})
    lib_symbols = "\n".join(symbol_def(s, LIB + ":") for s in used)
    sch = f"""(kicad_sch (version 20230121) (generator eeschema)
  (uuid {ROOT})
  (paper "A2")
  (title_block
    (title "Ultra Choc Wings, one half")
    (comment 1 "Generated from the routed board by scripts/make_schematic.py; rerun scripts/build_pcb.sh")
    (comment 2 "Reversible PCB: left half has parts on F, right half on B")
  )
  (lib_symbols
{lib_symbols}
  )
{chr(10).join(items)}
  (sheet_instances (path "/" (page "1")))
)
"""
    with open(path, "w") as f:
        f.write(sch)
    return instances


def write_symbol_lib(path):
    body = "\n".join(symbol_def(s) for s in sorted(SYMBOLS))
    with open(path, "w") as f:
        f.write(f"(kicad_symbol_lib (version 20220914) (generator kicad_symbol_editor)\n{body}\n)\n")


def write_lib_tables(outdir):
    with open(os.path.join(outdir, "fp-lib-table"), "w") as f:
        f.write(f'(fp_lib_table\n  (version 7)\n  (lib (name "{LIB}")(type "KiCad")(uri "${{KIPRJMOD}}/{LIB}.pretty")'
                f'(options "")(descr "Footprints of every part on the board"))\n)\n')
    with open(os.path.join(outdir, "sym-lib-table"), "w") as f:
        f.write(f'(sym_lib_table\n  (version 7)\n  (lib (name "{LIB}")(type "KiCad")(uri "${{KIPRJMOD}}/{LIB}.kicad_sym")'
                f'(options "")(descr "Symbols of every part on the board"))\n)\n')


# --- linking the board ------------------------------------------------------

def link_board(pcb_path, instances):
    """Point each footprint at its library footprint and schematic symbol.

    Works on the board file's text, so it handles any KiCad version's file."""
    src = open(pcb_path).read()
    # KiCad 8 and newer also write the sheet name and file next to the path.
    version = re.search(r"\(version (\d+)\)", src)
    sheet = bool(version) and int(version.group(1)) >= 20240108
    out, i = [], 0
    for m in re.finditer(r'\(footprint "([^"]+)"', src):
        if m.start() < i:
            continue
        depth, j = 0, m.start()
        while True:
            c = src[j]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            elif c == '"':
                j += 1
                while src[j] != '"':
                    j += 2 if src[j] == "\\" else 1
            j += 1
        block = src[m.start():j + 1]
        ref = re.search(r'\((?:property "Reference"|fp_text reference) "([^"]+)"', block)
        name = m.group(1).split(":")[-1]
        block = block.replace(m.group(0), f'(footprint "{LIB}:{name}"', 1)
        if ref and ref.group(1) in instances:
            block = re.sub(r'\n[ \t]*\((?:path|sheetname|sheetfile) "[^"]*"\)', "", block)
            nl = re.search(r"\n([ \t]*)\(", block)
            indent = nl.group(1) if nl else " "
            link = f'\n{indent}(path "/{instances[ref.group(1)]}")'
            if sheet:
                link += f'\n{indent}(sheetname "/")\n{indent}(sheetfile "{PROJECT}.kicad_sch")'
            # KiCad writes these just before (attr ...); fall back to the end of the header.
            attr = re.search(r"\n" + re.escape(indent) + r"\(attr\b", block)
            at = re.search(r"\n" + re.escape(indent) + r"\(at [^\n]*", block)
            head = attr.start() if attr else (at.end() if at else block.index("\n"))
            block = block[:head] + link + block[head:]
        out.append(src[i:m.start()])
        out.append(block)
        i = j + 1
    out.append(src[i:])
    with open(pcb_path, "w") as f:
        f.write("".join(out))


def main():
    pcb_path = sys.argv[1]
    link_path = sys.argv[2] if len(sys.argv) > 2 else pcb_path
    outdir = os.path.dirname(os.path.abspath(link_path))
    board = pcbnew.LoadBoard(pcb_path)
    plist = parts(board)
    fps = export_footprints(board, os.path.join(outdir, LIB + ".pretty"))
    write_symbol_lib(os.path.join(outdir, LIB + ".kicad_sym"))
    instances = write_schematic(plist, os.path.join(outdir, PROJECT + ".kicad_sch"))
    write_lib_tables(outdir)
    del board
    link_board(link_path, instances)
    print(f"wrote {PROJECT}.kicad_sch ({len(instances)} parts), {len(fps)} footprints, {len(SYMBOLS)} symbols")


if __name__ == "__main__":
    main()
