#!/usr/bin/env python3
"""Generate the uniboard case (OpenSCAD) from the routed PCB.

    python3 scripts/make_case.py pcb/ultra-choc-wings.kicad_pcb case/ultra_choc_wings_case.scad

The case is one piece that holds both halves at a fixed splay, so the split
keyboard becomes a uniboard. Board outline, M2 holes, XIAO and power switch
positions all come from the PCB, so the case follows any change to config.yaml.
Tweak the parameters at the top of the generated .scad file in OpenSCAD.
"""
import math
import sys

import pcbnew


def mm(v):
    return pcbnew.ToMM(v)


def outline(board):
    poly = pcbnew.SHAPE_POLY_SET()
    board.GetBoardPolygonOutlines(poly)
    chain = poly.Outline(0)
    # KiCad y points down; OpenSCAD y points up.
    return [(round(mm(chain.CPoint(i).x), 3), round(-mm(chain.CPoint(i).y), 3)) for i in range(chain.PointCount())]


def footprint_box(fp):
    box = fp.GetBoundingBox(False, False)
    return (mm(box.GetLeft()), -mm(box.GetBottom()), mm(box.GetRight()), -mm(box.GetTop()))


def main():
    pcb_path, out = sys.argv[1], sys.argv[2]
    board = pcbnew.LoadBoard(pcb_path)
    pts = outline(board)
    holes, xiao, switch, coin = [], None, None, None
    for fp in board.GetFootprints():
        ref = fp.GetReference()
        pos = fp.GetPosition()
        if ref.startswith("H"):
            holes.append((round(mm(pos.x), 3), round(-mm(pos.y), 3)))
        elif ref.startswith("xiao"):
            xiao = footprint_box(fp)
        elif ref.startswith("T"):
            switch = (round(mm(pos.x), 3), round(-mm(pos.y), 3))
        elif ref.startswith("BT"):
            coin = (round(mm(pos.x), 3), round(-mm(pos.y), 3))
    top = max(y for _, y in pts)

    # XIAO USB-C and the slide switch both stick out of the top edge; one
    # notch in the case wall covers both.
    notch = (round(xiao[0] - 1, 2), round(switch[0] + 5, 2))
    # XIAO pins poke through the bottom of the PCB.
    relief = [round(v, 2) for v in xiao]

    fmt = lambda ps: "[" + ", ".join(f"[{x}, {y}]" for x, y in ps) + "]"
    scad = f"""// Ultra Choc Wings uniboard case. Generated by scripts/make_case.py from the PCB;
// edit the parameters below, not the data.
//
// One piece holds both halves (left PCB switch side up, right PCB flipped)
// at a fixed splay. Each half drops into its pocket and sits flat on the
// floor (every SMD part is on the top side, so the bottom is bare), held by
// three M2 screws that self-tap into the floor. The CR2032 is reachable from
// the top; the top-edge notch clears the XIAO USB-C and the power switch.

/* [Layout] */
splay = 12;        // degrees each half is rotated away from straight
gap = 18;          // mm between the two halves at their closest point
/* [Walls] */
wall = 2.4;        // side wall thickness
floor_t = 3;       // floor under the PCB
clearance = 0.4;   // gap between PCB edge and pocket wall
pcb_t = 1.6;
lip = 1.0;         // wall height above the PCB top surface
/* [Screws] */
pilot_d = 1.7;     // M2 self-tapping pilot (use 3.2 for M2 heat-set inserts)
pilot_depth = 2.6;
/* [Details] */
xiao_relief_depth = 2;
notch_depth = 10;  // how far the top-edge notch reaches into the wall
center_tray = true; // hollow the deck between the halves
$fn = 48;

board = {fmt(pts)};
holes = {fmt(holes)};
xiao_relief = {relief}; // [x0, y0, x1, y1]
notch_x = {list(notch)};
board_top = {round(top, 3)};
coin = {list(coin)};

// Place the left half so its inner edge sits gap/2 left of x = 0.
function rot(p, a) = [p[0] * cos(a) - p[1] * sin(a), p[0] * sin(a) + p[1] * cos(a)];
inner_x = max([for (p = board) rot(p, -splay)[0]]);

module place_left() translate([-gap / 2 - inner_x, 0]) rotate(-splay) children();
module place_right() mirror([1, 0]) place_left() children();
module both() {{ place_left() children(); place_right() children(); }}

h = floor_t + pcb_t + lip;

module board_shape() polygon(board);

module outer_shape() offset(r = wall + clearance) hull() both() board_shape();

module pockets() both() offset(delta = clearance) board_shape();

module case() {{
    difference() {{
        linear_extrude(h) outer_shape();
        // PCB pockets
        translate([0, 0, floor_t]) linear_extrude(h) pockets();
        // Deck between the halves
        if (center_tray)
            translate([0, 0, floor_t]) linear_extrude(h)
                // offset in, then out: drops slivers too thin to be useful
                offset(r = 3) offset(delta = -3) difference() {{
                    offset(r = -wall) outer_shape();
                    offset(r = wall + clearance) both() board_shape();
                }}
        // XIAO pin relief
        translate([0, 0, floor_t - xiao_relief_depth]) linear_extrude(h)
            both() offset(delta = 1)
                translate([xiao_relief[0], xiao_relief[1]])
                    square([xiao_relief[2] - xiao_relief[0], xiao_relief[3] - xiao_relief[1]]);
        // USB-C / power switch notch in the top wall
        translate([0, 0, floor_t]) linear_extrude(h)
            both() translate([notch_x[0], board_top - 1])
                square([notch_x[1] - notch_x[0], notch_depth]);
        // M2 pilot holes
        both() for (p = holes) translate([p[0], p[1], floor_t - pilot_depth])
            linear_extrude(pilot_depth + 0.01) circle(d = pilot_d);
    }}
}}

case();
"""
    with open(out, "w") as f:
        f.write(scad)
    print(f"wrote {out}: {len(pts)} outline points, {len(holes)} holes")


if __name__ == "__main__":
    main()
