#!/usr/bin/env python3
"""Export the board geometry the cases are built around (OpenSCAD).

    python3 scripts/make_case.py pcb/ultra-choc-wings.kicad_pcb case/board.scad

Writes the board outline, M2 holes, key centres, and the XIAO, power switch
and CR2032 positions, all taken from the routed PCB, so both case designs
(`case/fold.scad` and `case/split.scad`) follow any change to config.yaml.
The case designs themselves are hand-written; this file is only their data.
"""
import sys

import pcbnew


def mm(v):
    return pcbnew.ToMM(v)


def point(pos):
    # KiCad y points down; OpenSCAD y points up.
    return (round(mm(pos.x), 3), round(-mm(pos.y), 3))


def outline(board):
    poly = pcbnew.SHAPE_POLY_SET()
    board.GetBoardPolygonOutlines(poly)
    chain = poly.Outline(0)
    return [point(chain.CPoint(i)) for i in range(chain.PointCount())]


def footprint_box(fp):
    box = fp.GetBoundingBox(False, False)
    return [round(mm(box.GetLeft()), 2), round(-mm(box.GetBottom()), 2),
            round(mm(box.GetRight()), 2), round(-mm(box.GetTop()), 2)]


def main():
    pcb_path, out = sys.argv[1], sys.argv[2]
    board = pcbnew.LoadBoard(pcb_path)
    pts = outline(board)
    holes, keys, xiao, switch, coin = [], [], None, None, None
    for fp in sorted(board.GetFootprints(), key=lambda f: f.GetReference()):
        ref = fp.GetReference()
        if ref.startswith("H"):
            holes.append(point(fp.GetPosition()))
        elif ref.startswith("SW"):
            # KiCad angles are counter-clockwise as drawn, same as OpenSCAD's.
            keys.append((*point(fp.GetPosition()), round(fp.GetOrientationDegrees(), 3)))
        elif ref.startswith("xiao"):
            xiao = footprint_box(fp)
        elif ref.startswith("T"):
            switch = point(fp.GetPosition())
        elif ref.startswith("BT"):
            coin = point(fp.GetPosition())
    top = max(y for _, y in pts)

    fmt = lambda ps: "[" + ", ".join("[" + ", ".join(str(v) for v in p) + "]" for p in ps) + "]"
    scad = f"""// Ultra Choc Wings board geometry, generated by scripts/make_case.py from
// pcb/ultra-choc-wings.kicad_pcb. Do not edit: rerun scripts/build_pcb.sh.
// Coordinates are the left half, switch side up, in mm, y up.

board = {fmt(pts)};
board_top = {round(top, 3)};
holes = {fmt(holes)};        // M2 mounting holes
keys = {fmt(keys)};          // switch centres [x, y, rotation]
xiao_box = {xiao};           // XIAO footprint [x0, y0, x1, y1]
power_switch = {list(switch)};   // slide switch centre, on the top edge
coin = {list(coin)};         // CR2032 holder centre
"""
    with open(out, "w") as f:
        f.write(scad)
    print(f"wrote {out}: {len(pts)} outline points, {len(holes)} holes, {len(keys)} keys")


if __name__ == "__main__":
    main()
